CREATE TABLE [Person] (
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	[Name] VARCHAR(200) NOT NULL,
	[BirthDate] DATETIME NOT NULL,
	[MailAddress] VARCHAR(200) NOT NULL,
	[City] VARCHAR(50) NOT NULL,
	[RegisterDate] DATETIME DEFAULT(GETDATE()),
	[Active] BIT DEFAULT(1)
);

CREATE TABLE [Document] (
	[IdPerson] UNIQUEIDENTIFIER,
	[Description] VARCHAR(200) NOT NULL,
	[Value] VARCHAR(50) NOT NULL,
	CONSTRAINT FK_Document_IdPerson FOREIGN KEY ([IdPerson]) REFERENCES [Person] ([Id])
); 
